# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: hyprsummon

builds:

  - id: hyprsummon
    main: .
    binary: hyprsummon
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - arm64
      - amd64

archives:

  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
